name: Generate Events

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generation script
        run: npm run generate

      - name: Commit and push generated files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add events/*.html
          # Commit only if there are changes
          git diff --cached --quiet || git commit -m "Add generated event HTML files"
          git push
