name: Generate Event Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies (if any)
      run: npm install

    - name: Generate event pages and sitemap
      run: node generate-events.js

    - name: Commit and push generated files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add events/
        git commit -m "Auto-generate event pages and sitemap" || echo "No changes to commit"
        git push
